services:
  nlp-medcat-service-production:
    container_name: cogstack-medcat-service-production
    ### Multiple images available:
    ## default image, only CPU support: cogstacksystems/medcat-service:latest 
    ## GPU support: cogstacksystems/medcat-service-gpu:latest
    # image: cogstacksystems/medcat-service:latest
    restart: always
    ## Default dockerfile: ../Dockerfile
    ## GPU dockerfile: ../Dockerfile_gpu
    build:
      context: ../
      dockerfile: "Dockerfile"
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
    env_file:
      - ../env/app.env
      - ../env/medcat.env
    volumes:
    - ../models:/cat/models/:rw
    ports:
      - "5555:5000"
    networks:
      - cognet

  nlp-medcat-service-production-1:
    container_name: cogstack-medcat-service-production-1-deid
    ### Multiple images available:
    ## default image, only CPU support: cogstacksystems/medcat-service:latest 
    ## GPU support: cogstacksystems/medcat-service-gpu:latest
    # image: cogstacksystems/medcat-service:latest
    restart: always
    ## Default dockerfile: ../Dockerfile
    ## GPU dockerfile: ../Dockerfile_gpu
    build:
      context: ../
      dockerfile: "Dockerfile"
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
    env_file:
      - ../env/app_1.env
      - ../env/medcat_1.env
    volumes:
    - ../models:/cat/models/:rw
    ports:
      - "5556:5000"
    networks:
      - cognet
      
networks:
  cognet:
    name: cogstack-net
