version: "3.6"

services:
  medcat-service:
    container_name: medcat-service
    ### Multiple images available:
    ## default image, only CPU support: cogstacksystems/medcat-service:latest 
    ## GPU support: cogstacksystems/medcat-service-gpu:latest
    # image: cogstacksystems/medcat-service:latest
    platform: linux
    restart: always
    ## Default dockerfile: ../Dockerfile
    ## GPU dockerfile: ../Dockerfile_gpu
    build:
      context: ../
      dockerfile: "Dockerfile"
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
    env_file:
      - ../envs/env_app
      - ../envs/env_medcat
    volumes:
    - ../models/medmen/:/cat/models/:rw
    ports:
      - "5555:5000"

