version: '3.5'

services:
  medcat-service:
    build: ..
    restart: always
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
    env_file:
      - ../envs/env_app
      - ../envs/env_medcat
    volumes:
    - ../models/medmen/vocab.dat:/cat/models/vocab.dat:ro
    - ../models/medmen/cdb.dat:/cat/models/cdb.dat:ro
    - ../models/medmen/Status:/cat/models/Status:ro
    #- ../models/modelpack.zip:/cat/models/modelpack.zip:ro

    ports:
      - "5000:5000"

