version: "3.6"

services:
  medcat-service:
    platform: linux
    build: ..
    restart: always
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
    env_file:
      - ../envs/env_app
      - ../envs/env_medcat
    volumes:
    - ../models/medmen/:/cat/models/:rw
    ports:
      - "5000:5000"

