version: '3.5'

services:
  medcat-service:
    build: ..
    env_file:
      - ../envs/env_app
      - ../envs/env_medcat
    volumes:
    - ../models/medmen/vocab.dat:/cat/models/vocab.dat:ro
    - ../models/medmen/cdb.dat:/cat/models/cdb.dat:ro
    - ../models/medmen/Status:/cat/models/mc_status:ro
    ports:
      - "5555:5000"
