name: Run tests

on:

  push:
    branches: [ devel, master ]
  pull_request:
    branches: [ devel, master ]
    
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          sudo apt-get install -y isort flake8
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv venv-test
          source venv-test/bin/activate
          python -m pip install -r medcat_service/requirements.txt
          python -m pip install isort flake8 mypy types-Flask

      - name: Check linting and types
        run: |
          isort -rc .
          flake8 .
          mypy . --ignore-missing-imports

      - name: Run tests
        run: bash run_tests.sh
      
     
