name: Run tests

on:

  push:
    branches: [ devel, main ]
  pull_request:
    branches: [ devel, main ]
    
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Cache MedMen Model
        id: cache-medmen
        uses: actions/cache@v4
        with:
          path: models/medmen
          key: medmen-${{ hashFiles('scripts/download_medmen.sh') }}

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          sudo apt-get install -y isort flake8
          python -m pip install --upgrade pip
          python -m pip install virtualenv setuptools
          python -m pip install isort flake8 mypy stubs types-Flask types-simplejson types-setuptools types-requests
          python -m pip install -r ./requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu/;

      - name: Check linting and types
        run: |
          isort .
          flake8 .
          mypy . --ignore-missing-imports

      - name: Run tests
        run: bash run_tests.sh
      
     
